
/*
 * BLLibraryBase
 * ------------------------------
 * A library is a group of designs
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_library.cpp instead
 *
 */

#pragma once

using namespace std;

#include <memory>
#include "bl_observer.h"
#include <list>
#include <string>
#include <list>
class BLDesign;

class BLLibraryBase
{
    
    string name;
    list<shared_ptr<IBLObserver<string>>> name_observers;
    
    list<string> filenames;
    list<shared_ptr<IBLObserver<string>>> filenames_observers;
    
    list<shared_ptr<BLDesign>> designs;
    list<shared_ptr<IBLObserver<shared_ptr<BLDesign>>>> designs_observers;
    
public:
    
    string get_name();
    void observe_name(shared_ptr<IBLObserver<string>> observer);
    void set_name(string value);
    
    list<string> get_filenames();
    void observe_filenames(shared_ptr<IBLObserver<string>> observer);
    void add_filename(string value);
    
    
    list<shared_ptr<BLDesign>> get_designs();
    void observe_designs(shared_ptr<IBLObserver<shared_ptr<BLDesign>>> observer);
    void add_design(shared_ptr<BLDesign> value);
    
    

};
