
/*
 * BLLibraryBase
 * ------------------------------
 * A library is a group of designs
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_library.h instead
 *
 */

#include "bl_library_base.h"


    string BLLibraryBase::get_name()
    {
        return this->name;
    }

    void BLLibraryBase::set_name(string value)
        {
            this->name = value;
        }
    

    list<string> BLLibraryBase::get_filenames()
    {
        return this->filenames;
    }

    
        void BLLibraryBase::add_filename(string value)
        {
            this->filenames.push_back( value );
        }
    

    list<shared_ptr<BLDesign>> BLLibraryBase::get_designs()
    {
        return this->designs;
    }

    
        void BLLibraryBase::add_design(shared_ptr<BLDesign> value)
        {
            this->designs.push_back( value );
        }
    
