
/*
 * BLLibraryBase
 * ------------------------------
 * A library is a group of designs
 *
 * IMPORTANT NOTE: DO NOT EDIT THIS FILE, edit bl_library.cpp instead
 *
 */

#pragma once

using namespace std;

#include <memory>
#include <string>
#include <list>
// //     #include "bl_design.h"
// 
class BLDesign;

class BLLibraryBase
{
    
        string name;
    
        list<string> filenames;
    
        list<shared_ptr<BLDesign>> designs;
    
    public:
        
            string get_name();
            
                void set_name(string value);
            
        
            list<string> get_filenames();
            
                void add_filename(string value);
            
        
            list<shared_ptr<BLDesign>> get_designs();
            
                void add_design(shared_ptr<BLDesign> value);
            
        

};
